#!/usr/bin/env bash

if [ ! -d ~/.gabriel ] ; then
  mkdir -p ~/.gabriel
fi

cp -f `pwd`/scripts/gabriel.bash ~/.gabriel/gabriel.bash

touch ~/.bashrc
grep "gabriel.bash" ~/.bashrc > /dev/null
if [ $? != 0 ] ; then
  echo "" >> ~/.bashrc
  echo "source ~/.gabriel/gabriel.bash" >> ~/.bashrc
fi

printf "DONE! To activate the installed completions:\n\n"
printf "1) Ensure that ~/.bashrc is sourced from your profile (~/.bash_profile or ~/.profile):\n"
printf "$ echo \"source ~/.bashrc\" >> ~/.bash_profile\n\n"
printf "2) Exit and re-enter your shell or issue the following command:\n"
printf "$ source ~/.gabriel/gabriel.bash\n\n"
printf "Enjoy!  -- Enrico B\n"
